### PR TITLE
Add python3 support

### LINKED ISSUE #1: Fix installation dependencies
Most simulator depend on this repo. We need to be able to automatically install orocos-KDL, to use it in our tests.

### PR DESCRIPTION
**Pull request by jprltsnz**
Python3 support added. This repo won't follow the standard lab procedure for migration since the bindings are automatically generated. This PR does 3 things:

1. Rename Joint::None (Joint.None in python) to Joint::NoJoint (Joint.NoJoint in python). This is needed because the Joint.None is invalid python3 syntax. This is a breaking change, all code needs to be updated.

2. Since python3 and python2 string management is different this inserts some if to handle that, and turn a few things to Unicode on the python side. Possibly breaking, but only on poorly handled python strings on our side. 

3. Add the upstream unit tests. This gives us more confidence that the repo works as expected. The only tests that fail are the Pickle test. Since this is won't block usage I will fix this later. The Pickle tests have been commented out for the time-being.

Fixes #1, in the sense that this allows to test both python versions, however each repo still needs to compile this on their own to use this on their own test cases.

### CODE REVIEW

**Comment by jprltsnz** [comment]
@degv364 , @rlmrjmnz  please review this as soon as you can as this blocks our migration efforts

**Comment by degv364** [comment]
@jcrono I see that you changed None to NoJoint. if I understand correctly, we will have to change  our python code to use NoJoint? or this is something that is solved by sip?

I guess NoJoint is valid for python2 also?

**Review by degv364 — COMMENTED** [review]
We are diverging a lot from their code by fixing identation. It looks better now, but I am not sure if we really want to diverge so much...

**Comment by jprltsnz** [comment]
> @jcrono I see that you changed None to NoJoint. if I understand correctly, we will have to change our python code to use NoJoint? or this is something that is solved by sip?
>
> I guess NoJoint is valid for python2 also?

Yes, code that is calls Joint.None needs to change to Joint.NoJoint, if not it will be broken. Joint.None will return an attribute error in python because is doesn't exists, regardless of python version. I opted to change Joint.None to Joint.NoJoint in both version.

The alternative is to just change Joint.NoJoint for python 3 but, if I do that we would require something like this:
``` python
try:
     Joint.NoJoint
except AttributeError:
     Joint.None
```
Since we are trying to support both version of python out of the same code base, we will get quite a few of those `try: .. except:` Which would cumbersome. I prefer to break our current python 2 code and force it to use python 3 conventions, especially since python 2 end of life is not that much into the future and we don't really have any technical reasons to use python 2.

**Comment by jprltsnz** [comment]
> We are diverging a lot from their code by fixing identation. It looks better now, but I am not sure if we really want to diverge so much...

I didn't fix any indentation. Our patches are, in fact, poorly formatted. The lines that change were using mix tab and spaces, which got fixed by my editor and turned into just spaces.

Also all the lines that change are in *our changes* so we are not diverging any more than with just applying the patches we need. 

In any case our code has diverged enough that we need to use a version of upstream from 2012, since Our patches can't be applied to anything more recent. It is worthy to port our changes to the latest upstream version, but it will take a substantial effort that would block any improvements in the rest of our code for a long time. So I don't think keeping up with upstream is a priority especially in formatting, what we should not try is to insert new features (if they are ever needed) until we can update to the lastest upstrea,.

**Review by degv364 — APPROVED** [review]

**Comment by rlmrjmnz** [comment]
> We are diverging a lot from their code by fixing identation. It looks better now, but I am not sure if we really want to diverge so much...

As @jcrono said, this is no a big problem since we are using our own Orocos' version, because of some chained joints and other stuff that the main Orocos' version doesn't have. It will be great to update our version, but that's a lot of work by now. Maybe we can think about using a Mediator Pattern to encapsulate Joint.None in Joint.NoJoint and applying as a patch to the latest upstream.   

>  I prefer to break our current python 2 code and force it to use python 3 conventions, especially since python 2 end of life is not that much into the future and we don't really have any technical reasons to use python 2.

I prefer that too, Python 2 doesn't have any technical standout against Python 3 in our case and using Python 3 will help to the maintainability of the project.

With that said, I'm going to approved these changes and merge the PR.

**Review by rlmrjmnz — APPROVED** [review]

**Pull request merged**
